### ISSUE TITLE
large video not uploading with setVideoData

### ISSUE THREAD

**Issue by kuldeep13990** [mtrung/TwitterVideoUpload#1]
i am trying to upload video on twitter, by using **setVideoData** method i am able to upload video, but when  i try to upload large like 10 mb , it fire the error, video size is long.

can you suggest me how to upload large video with **addVideoChunk** method?

thanks

**Comment by mtrung** [comment]
There are a few items to keep in mind when uploading video:
- The maximum file size is 15MB and is checked during the upload process
- The maximum length is 30 seconds and is checked when Tweeting with a video media_id

Could you check your file?

**Comment by kuldeep13990** [comment]
@mtrung , my question is how can i upload large video (5 minutes, 30 mb) with addVideoChunk metho.

**Comment by mtrung** [comment]
@kuldeep13990 it's impossible: max file size is 15MB as mentioned above.
